name: Deploy with Helm

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: aws/setup-helm@v3
        with:
          version: v3.14.0

      - name: Deploy Helm chart
        run: |
          helm upgrade --install mywebapp ./my-webapp
