name: Deploy to Kubernetes with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: configure  Kubernetes
        uses: aws/k8s-set-context@v3

      - name: install  Helm chart
        run: |
          helm upgrade --install my-webapp ./webapp --namespace default --set image.tag=${{ github.sha }} --wait